image: gcr.io/kaniko-project/executor:debug

stages:
  - setup
  - triggers
  - build
  - devops-build

services:
  # - docker:18-dind # TODO: test the docker changes with last images
  - docker:20.10-dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-admin

# TODO: handle cache
# cache: &global_cache
#   key: ${DOCKER_DIRECTORY}-${PROJECT}
#   paths:
#     - ${DOCKER_DIRECTORY}/${PROJECT}/kaniko/cache

build:
  stage: build
  # TODO: ignore devops to avoid changes
  except:
    - feat/devops-images
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/node/Dockerfile --destination "$CI_REGISTRY_IMAGE/node:latest"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/node/frontend.Dockerfile --destination "$CI_REGISTRY_IMAGE/frontend:latest"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/openjdk/Dockerfile --destination "$CI_REGISTRY_IMAGE/openjdk:latest"

generate-config-images:
  image: python:3.8-alpine
  before_script: pip install pyyaml
  stage: setup
  only:
    - feat/devops-images
  script:
    - python templates/generate-repos.py --file build-images.yaml
  artifacts:
    paths:
      - templates/build-images.yaml

trigger-docker-builds:
  stage: triggers
  only:
    - feat/devops-images
  trigger:
    include:
      - artifact: templates/build-images.yaml
        job: generate-config-images

docker-build:
  stage: devops-build
  only:
    - feat/devops-images
  script:
    - bin/build ${CI_REGISTRY_IMAGE}
  interruptible: true
  # cache:
  #   <<: *global_cache
